spring:
  application:
    name: QuickStartSpringBoot
  freemarker:
    template-loader-path: classpath:templates/ # or put the system location like this file:/opt/tomcat/freemarker-template/
    cache: false
    check-template-location: true
  mail:
    host: <<hostname>>
    port: <<port>>
    username: <<userName>>
    password: <<password>>
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    default-encoding: UTF-8
server:
  port: 8080



