spring:
  datasource:
    url: jdbc:mysql://coofun.local:3306/app_db_001
    username: root
    password: root
  application:
    name: QuickStartSpringBoot
  flyway:
    enabled: true
    user: root
    password: root
    locations: classpath:db/migration
    url: jdbc:mysql://coofun.local:3306/app_db_001
    baseline-on-migrate: true
    sql-migration-prefix: V_
server:
  port: 8080

