spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
  application:
    name: QuickStartSpringBoot
  datasource:
    url: jdbc:mysql://coofun.local:3306/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

app:
  default:
    minute: 00
    hour: 03

